[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", ".git"]
language-servers = ["pyright"]
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }


[[language]]
name = "c"
[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "/opt/homebrew/opt/llvm/bin/lldb-dap"
[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [{ name = "binary", default = "main" }]
[language.debugger.templates.args]
program = "{0}"
